N_EPISODES: 1
WINDOW_H: 600
WINDOW_W: 600

TRUCK:
  ORIGIN_POS_X: 0
  ORIGIN_POS_Y: 0
  CAPACITY: 1000

REWARD:
  IDLE: -.01
  STEP: -.1
  COLLISION: 100
  RIGHT_DIRECTION: 1
  FILLED_EMPTIED: 10

ENV:
  MARGIN: 50
  GEN_MAP:
    MIN_H: 50
    MIN_W: 50
    MAX_H: 100
    MAX_W: 100
    SEED:  null
    N_EXCAVATORS: 3
    MASS_PER_HOLE: 1000

DQN:
  BATCH_SIZE: 128
  GAMMA: .99
  EPS_START: .9
  EPS_END: .05
  EPS_DECAY: 1000
  TAU: .005